# Site settings
title: From People to Python
description: My Data Science Portfolio
baseurl: ""
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sijana Mamos
user_description: From People to Python | Data Science & Machine Learning | Bridging Behavioural Science and Tech
user_title: Data Scientist
email: sijana.mamos@gmail.com
twitter_username: lorem_ipsum
github_username:  Sijana
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
